### ISSUE TITLE
nom v4 support

### ISSUE THREAD

**Issue by xpayn** [fflorent/nom_locate#14]
Hi!
nom v4 was just released, and i was wondering if you are planning to support this new version.
i'm currently trying to parse a text format and would appreciate to be able to report faulty line and column when an error occurs.
Anyway, as i'm knee deep in nom right now, i can try to do it myself, but i guess a little help would be needed as i'm fairly knew to rust, nom and library writing.

**Comment by xpayn** [comment]
well... i've just seen the pending PR about it

**Comment by fflorent** [comment]
Hello,

Yes, indeed. Christopher is about to work on it : https://github.com/fflorent/nom_locate/pull/10#issuecomment-389713908

Florent

**Comment by xpayn** [comment]
That's great!
By the way, do you know some open source project which use nom_locate?
I'd like to see what a real life example looks like.

**Comment by sunjay** [comment]
#10 just landed! This issue can probably be closed.

To answer your question, I have [a project](https://github.com/sunjay/lion/blob/master/src/parser.rs) that uses this crate, but there are others that are more robust and interesting.

**Comment by fflorent** [comment]
Yay, however I still have some work until the new version is published (mostly tests). But don't worry, it will be released very soon :).

Florent

**Comment by fflorent** [comment]
nom_locate v0.3.0 released :)
 - changelog: https://github.com/fflorent/nom_locate/blob/b1518af5a2214855ba0f559ce5c9b94c0686fb28/CHANGELOG.md
 - crate: https://crates.io/crates/nom_locate
