### ISSUE TITLE
Use with verbose-errors feature

### ISSUE THREAD

**Issue by AljoschaMeyer** [fflorent/nom_locate#17]
Hey,

is it possible to use this crate with nom's verbose-errors feature? Enabling the verbose-errors feature for nom_locate does not help, compilation still fails [here](https://github.com/fflorent/nom_locate/blob/master/src/lib.rs#L300).

```
    |
279 |                 match e {
    |                       ^ pattern `Error(List(_))` not covered

```

nom version `4.0.0`, nom_locate version `0.3.0`

**Comment by ProgVal** [comment]
Thanks for the report, this should be fixed by commit c97835d.

**Comment by AljoschaMeyer** [comment]
Yay, thank you for the quick fix.

**Comment by tstack** [comment]
Looks like this is broken again:

```
error[E0004]: non-exhaustive patterns: `Error(List(_))` not covered
   --> /Users/stack/.cargo/registry/src/github.com-1ecc6299db9ec823/nom_locate-0.3.1/src/lib.rs:299:23
    |
299 |                 match e {
    |                       ^ pattern `Error(List(_))` not covered

error[E0004]: non-exhaustive patterns: `Error(List(_))` not covered
   --> /Users/stack/.cargo/registry/src/github.com-1ecc6299db9ec823/nom_locate-0.3.1/src/lib.rs:324:23
    |
324 |                 match e {
    |                       ^ pattern `Error(List(_))` not covered
```

**Comment by ProgVal** [comment]
@tstack You need to enable the `verbose-errors` feature of `nom_locate` (in addition to `nom` itself).

**Comment by tstack** [comment]
Sorry, didn't realize, my bad.
