### ISSUE TITLE
Release 0.3.1?

### ISSUE THREAD

**Issue by sunjay** [fflorent/nom_locate#18]
The bugfix made recently isn't released to crates.io yet. Could you make a patch release?

Thanks for this crate!

**Comment by fflorent** [comment]
You're right. Sorry for the delay!

That's published now. Thanks for using it!
Florent

**Comment by sunjay** [comment]
Thank you!

**Comment by fflorent** [comment]
You're highly welcome. Thanks to @ProgVal for the fixes provided ;)
