### ISSUE TITLE
Adding extra information to LocatedSpan

### ISSUE THREAD

**Issue by peckpeck** [fflorent/nom_locate#21]
I am writing a parser and I would like to retain informations about parsed data location in parser output to help my user.
I found that using LocatedSpan in both my inputs and my outputs is a good way to do that. 

However I would like to have more information without having to explicitely copy it each time i use a LocatedSpan, for example the parsed file name.

How about adding a type parameter to allow for extra storage in LocatedSpan ?
Ex: LocatedSpan<T,U> where u could be provided at construction time and then carried out each time a new Span is created

**Comment by orthoxerox** [comment]
Something like this? https://github.com/orthoxerox/nom_locate/tree/extra_info

**Comment by fflorent** [comment]
Hi, 

Sorry for not answering rapidly.

@orthoxerox Thanks a lot for your proposal! :tada: 

I'll take a look at all of this this weekend. 

@ProgVal may you also want to also take a look on your side?

Florent

**Comment by fflorent** [comment]
@orthoxerox would you like to open a PR so we can review this?

Florent

**Comment by orthoxerox** [comment]
@fflorent #22

**Comment by peckpeck** [comment]
Yes something like this.

**Comment by ProgVal** [comment]
Resolved by #28
