### ISSUE TITLE
Usage with nom 5.0

### ISSUE THREAD

**Issue by dalance** [fflorent/nom_locate#30]
I want to use nom_locate with nom 5.0.
But I wonder how to use it because the samples in README are based on macro parser.
I wrote a sample like below:

```rust
use nom::bytes::complete::*;
use nom::character::complete::*;
use nom::IResult;
use nom_locate::LocatedSpan;

type Span<'a> = LocatedSpan<&'a str>;

pub fn parser(s: Span) -> IResult<Span, Span> {
    let (s, _) = multispace0(s)?;
    let (s, a) = tag("a")(s)?;
    Ok((s, a))
}

#[cfg(test)]
mod tests {
    use super::*;
    use nom::combinator::*;

    #[test]
    fn test() {
        let (_, ret) = all_consuming(parser)(Span::new("   \n   \n   a")).unwrap();
        assert_eq!(
            format!("{:?}", ret),
            "LocatedSpanEx { offset: 11, line: 3, fragment: \"a\", extra: () }"
        );
    }
}
```

It seems to work fine. Is this usage is correct?
I can't understand the usage of `position!`. Is it unnecessary?

**Comment by ProgVal** [comment]
> It seems to work fine. Is this usage is correct?

To be honest, I don't really know, because I didn't get around trying nom 5 yet. But it looks right.

>  I can't understand the usage of `position!`. Is it unnecessary?

It is necessary if you want to get the position of a token in the middle of the string. In your example, still get it because you're kind of cheating, your function returns a Span. But it wouldn't work if you wanted your parser to return any type other than a string.

**Comment by dalance** [comment]
Thanks. I tried to define `position` for nom 5.0.

```rust
type Span<'a> = LocatedSpan<&'a str>;

#[derive(Debug)]
pub struct Token<'a> {
    p: Span<'a>,
    a: String,
}

pub fn position(s: Span) -> IResult<Span, Span> {
    take(0usize)(s)
}

pub fn parser(s: Span) -> IResult<Span, Token> {
    let (s, _) = multispace0(s)?;
    let (s, p) = position(s)?;
    let (s, a) = tag("a")(s)?;
    Ok((
        s,
        Token {
            p,
            a: a.to_string(),
        },
    ))
}
```

I think current master branch seems to work fine with nom5.0.
Could you release to crates.io?

**Comment by ProgVal** [comment]
Could you send a PR to add this `position` function directly to `nom_locate`, along with some tests and an updated readme? Thanks!

Otherwise I can do it myself later this week.

In any case, I'll ask the owner of `nom_locate` to do a release as soon as it's done

**Comment by dalance** [comment]
I sent a PR to add the function and README update.
