### ISSUE TITLE
Request to add LICENCE file

### ISSUE THREAD

**Issue by rekanorman** [fflorent/nom_locate#42]
Hi Florent,

We are hoping to use the nom_locate library in Google's Fuchsia OS. Is there any chance of adding a LICENCE file to the root directory? I would be happy to make the PR myself, if you let me know what the date and copyright owner should be.

Also, this is less important, but would it be possible to change the text in benches/benches.rs to something in the public domain? 

Thanks,
Reka

**Comment by fflorent** [comment]
Hi Reka,

Thanks for the report. Obviously the project is in MIT license. I made a PR so @ProgVal can also review it.

Florent

**Comment by rekanorman** [comment]
Thanks for that!

Regarding the text in benches/benches.rs, it seems that Camus' Plague might still be copyrighted. To avoid having to change the text, would it be possible to just add the benches directory to the package's [exclude section](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional)?

Reka

**Comment by rekanorman** [comment]
@fflorent just checking that you also saw my previous comment here?

**Comment by fflorent** [comment]
@rekanorman Working on it right now.

**Comment by fflorent** [comment]
I think a Polish text could be interesting (like Pan Tadeusz). Seems like this language has lots of diacritics.

**Comment by fflorent** [comment]
> Regarding the text in benches/benches.rs, it seems that Camus' Plague might still be copyrighted. To avoid having to change the text, would it be possible to just add the benches directory to the package's exclude section?

@rekanorman I changed the text so the benchmark can remain in MIT license. I guess it should be all fine now.

Happy new year!
Florent

**Comment by rekanorman** [comment]
@fflorent Thanks for getting this sorted out, it's much appreciated.

Happy new year to you too!
Reka
