### ISSUE TITLE
UB in get_columns_and_bytes_before

### ISSUE THREAD

**Issue by 0xd34d10cc** [fflorent/nom_locate#45]
The following code:
```rust
use nom_locate::LocatedSpan;

fn main() {
    let fragment = [b'a', b'b', b'c', b'd'];
    let span = LocatedSpan {
        offset: 12345,
        line: 0,
        fragment: std::str::from_utf8(&fragment).unwrap(),
        extra: ()
    };

    println!("{}", span.get_utf8_column());
}
```
prints random garbage value. 

The problem is here: 
https://github.com/fflorent/nom_locate/blob/504e84930bb132b647af8b983d0ba1b1a2fe525a/src/lib.rs#L216-L223
There is no guarantee that `self.offset` bytes before `self.fragment.as_bytes().as_ptr()` are actually readable.

**Comment by ProgVal** [comment]
Can this happen without constructing a LocatedSpan manually? I don't see any reason to do that; we should probably add an empty private field so it doesn't happen.

**Comment by 0xd34d10cc** [comment]
> Can this happen without constructing a LocatedSpan manually? 
Well, `offset` field is public, nothing prevents users from changing its value after construction.

**Comment by ProgVal** [comment]
indeed
