### ISSUE TITLE
Panic in `impl Offset for LocatedSpanEx` with `recognize`

### ISSUE THREAD

**Issue by torokati44** [fflorent/nom_locate#48]
When porting [this basic parser](https://gist.github.com/torokati44/238797a34e4533f934f0a007c50b12d2) to [this one using nom_locate](https://gist.github.com/torokati44/9317c84794b7491c6227dafd3629b9f9), I get an `'attempt to subtract with overflow'` panic [here](https://github.com/fflorent/nom_locate/blob/887f7b406173ae940dd6761dac0cf6a5a08a68e0/src/lib.rs#L669).
The first parser, without `nom_locate`, works just fine.
The panic reproduces with both the version on crates.io (1.0.0), and with latest git as of now.

**Comment by torokati44** [comment]
All those `all_consuming` wrappers in the `println!` calls are unnecessary of course, but don't seem to make a difference.
Also, by "working fine", I mean that at least it doesn't panic, not necessarily that it produces any kind of desirable output. :roll_eyes:

**Comment by ProgVal** [comment]
Hi,

This is caused by your use of `Span::new` in a parser function; which creates a new Span with offset 0.

However, when doing span computation, `nom_locate` assumes all spans' offset is with respect to the same string.

A fix for your issue is to use the `nom::trait::Slice` trait:

```
fn parse_string_content(buf: Span) -> Result<Span> {
    for (i, ch) in buf.fragment.char_indices() {
        if ch == '"' {
            return Ok((buf.slice(i..), buf.slice(i..i)));
        }
    }
    Err(nom::Err::Incomplete(nom::Needed::Unknown))
}
```

**Comment by torokati44** [comment]
Ooh, I see... And indeed, your fix works perfectly. Thank you so much!
