### ISSUE TITLE
Publish version with recent changes to crates.io

### ISSUE THREAD

**Issue by rekanorman** [fflorent/nom_locate#49]
Hi, would you mind publishing a new version to crates.io which contains the recent changes (license text and updated nom dependency).

**Comment by ProgVal** [comment]
I want to fix #45 first, then I'll ping Florent to release a new major version

**Comment by ProgVal** [comment]
It's fixed now (it was easier than I expected). A new version will be published when Florent is available

**Comment by rekanorman** [comment]
Thanks!

**Comment by fflorent** [comment]
Done!

Thanks everyone for your valuable contributions! :heart: 
Florent
