### ISSUE TITLE
Implement From<&str> for easier testing

### ISSUE THREAD

**Issue by jamwaffles** [fflorent/nom_locate#54]
Would it make sense to `impl<'a> From<&'a str> for LocatedSpan`? I'm refactoring a project to use nom_locate and a lot of my tests are bloating a bit:

```diff
- assert_eq!(units("G20"), Ok(("", Units::Inch)));
+ assert_eq!(
+     units(ParseInput::new("G20")),
+     Ok((ParseInput::new(""), Units::Inch))
+ );
```

It would be great to be able to call `.into()` so we get this:

```rust
assert_eq!(units("G20".into()), Ok(("".into(), Units::Inch)));
```

I'm happy to prep a PR, I just want to check if this is the right direction to go in.

Edit: I should mention that:

```rust
type ParseInput<'a> = LocatedSpan<&'a str>;
```

**Comment by kenaniah** [comment]
@ProgVal I noticed after implementing that some of the other traits can be further generalized thanks to `Into`. I'm hoping to have another PR to make more of this library generic within the next  hour or so. Thanks!
