### ISSUE TITLE
Can't de-structure a LocatedSpan to take ownership of its fragment or extra data

### ISSUE THREAD

**Issue by josh-berry** [fflorent/nom_locate#62]
Hi—first off, thank you for writing nom_locate! It's definitely made my life easier and I can't imagine using nom without it.

There is one thing I'd like to ask, though—because the `fragment` field is private inside the struct (in favor of using an accessor method), there is no way to de-structure a LocatedSpan to take ownership of the fragment.

For example, I was trying to write a trivial generic function to "unwrap" a LocatedSpan and get its fragment, and there is no way to get this to compile (at least, not without special-casing it further, e.g. adding a `Clone` or `Copy` bound to `I`):

```rust
use nom::AsBytes;
use nom::combinator::map;
use nom::error::ParseError;
use nom::IResult;
use nom_locate::LocatedSpan;

pub fn unwrap_span<P, I, X, E>(parser: P) -> impl Fn(LocatedSpan<I, X>) -> IResult<LocatedSpan<I, X>, I, E>
    where P: Fn(LocatedSpan<I, X>) -> IResult<LocatedSpan<I, X>, LocatedSpan<I, X>, E>,
          I: AsBytes,
          E: ParseError<LocatedSpan<I, X>>
{
    map(parser, |span| span.fragment()) // oops, can't move fragment out of span
}
```

Would you consider providing a way to extract the fragment and extra data from the LocatedSpan? Something like:

```rust
pub fn take(self) -> (I, X) { (self.fragment, self.extra) }
pub fn take_fragment(self) -> I { self.fragment }
pub fn take_extra(self) -> X { self.extra }
```

You might also want to add a `fragment_mut()` accessor since there is also no way to mutate a fragment inside a `LocatedSpan` presently.

Or even better, just make both `fragment` and `extra` be public fields. Then you could eliminate the `fragment()` accessor entirely.

Thanks!

**Comment by ProgVal** [comment]
The fragment is typically a slice over an array/string that `nom_locate` doesn't own (eg. `&str` or `&[u8]`), so `LocatedSpan::fragment()` returns a reference to a slice (ie. `&&str` or `&&[u8]`) so you just need to dereference them to get a copy of the slice (ie. a `&str` or `&[u8]`), which you own.

In your example, it would be:

```
extern crate nom;
extern crate nom_locate;

use nom::AsBytes;
use nom::combinator::{map, rest};
use nom::error::ParseError;
use nom::IResult;
use nom_locate::LocatedSpan;

pub fn unwrap_span<P, I, X, E>(parser: P) -> impl Fn(LocatedSpan<I, X>) -> IResult<LocatedSpan<I, X>, I, E>
    where P: Fn(LocatedSpan<I, X>) -> IResult<LocatedSpan<I, X>, LocatedSpan<I, X>, E>,
          I: AsBytes + Copy,
          E: ParseError<LocatedSpan<I, X>>
{
    map(parser, |span| *span.fragment())
}

fn main() {
    let prog: &[u8] = b"foo bar baz";
    let span = LocatedSpan::new(prog);
    let res: IResult<_, _, ()> = unwrap_span(rest)(span);
}
```

Am I missing something?

**Comment by josh-berry** [comment]
Hi, thanks for your response! I certainly agree `&str` and `&[u8]` are the most common cases (and that includes my project as well, at least for now), but like I said in my original post, my objective was to write something generic that would work no matter what type was being used with `LocatedSpan`—that means not adding extra bounds (like `Copy` or `Clone`) beyond what is required by `LocatedSpan` itself.

For now I have added `Clone` to my function to fix my immediate problem, but it still seems like a problem in the LocatedSpan API to me, because there is nothing about the `AsBytes` trait that requires an implementing type to be a reference at all—it merely requires there's a way to get a `&[u8]` by calling `whatever.as_bytes()`. So it is quite possible to have a `LocatedSpan` which contains a fragment that is neither `Copy` nor `Clone`. In those situations, it seems to me that being able to de-structure the LocatedSpan in some way (preferably to get both `fragment` and `extra` out) would be a necessity.

**Comment by ProgVal** [comment]
Yeah, you're right.

But `LocatedSpan<T>` needs to implement of nom traits, and `nom_locate` only implements them when `T` is `&str` or `&[u8]` so using a different type won't be trivial.

**Comment by pitaj** [comment]
What about a new function:
```rust
fn destructure(self) -> (T, X) {
    let LocatedSpan { fragment, extra } = self;
    (fragment, extra)
}
```

**Comment by mpizenberg** [comment]
Hi, I've just started a nom5 to nom7 update on some code base and stumbled upon [this line in our code base](https://github.com/rust-spandex/spandex/blob/37df236e99b2471da42515c63a3b0628ac8e9ef6/src/parser/combinators.rs#L263):
```rust
    span.fragment = span.fragment.trim_end();
```
I'm not sure how to do something similar since now the `fragment` is private. Any idea?

**Comment by progval** [comment]
@mpizenberg I'm moving this discussion here: #81

**Comment by mpizenberg** [comment]
Is this correct and safe? (our `Span` has no extra info)
```rust
/// Trim the end of the fragment.
/// This uses Span::new_from_raw_offset() which is marked `unsafe` but I believe this operation is
/// safe so I didn't mark this function as unsafe too.
fn trim_fragment_end<'a>(span: &Span<'a>) -> Span<'a> {
    unsafe {
        Span::new_from_raw_offset(
            span.location_offset(),
            span.location_line(),
            span.fragment().trim_end(),
            span.extra,
        )
    }
}
```
