### ISSUE TITLE
Next release for nom 6

### ISSUE THREAD

**Issue by dalance** [fflorent/nom_locate#68]
Is there any plan of a next release ( maybe v3.0.0? ) for nom 6 support?

**Comment by lukechu10** [comment]
A release would be really welcome. I have a crate that relies on `nom_locate` with `nom@6`. I can not publish it to crates.io because `nom_locate` is a git dependency right now. Thanks!

**Comment by ProgVal** [comment]
ack, let's try to do it this week

**Comment by bikeshedder** [comment]
`nom_locate 3.0.0` was released on crates.io a few hours ago: https://crates.io/crates/nom_locate/3.0.0 :tada: 

Thanks a lot! :+1:

**Comment by fflorent** [comment]
Yes! (sorry for not notifying)

Happy coding!
