### ISSUE TITLE
Unit tests in documentation don't compile, no obvious fix

### ISSUE THREAD

**Issue by rodya-mirov** [fflorent/nom_locate#71]
Hello, I'm looking at the crates.io documentation's sample usage (which is very much like a unit test):

```
extern crate nom;
extern crate nom_locate;

use nom::bytes::complete::{tag, take_until};
use nom::IResult;
use nom_locate::{position, LocatedSpan};

type Span<'a> = LocatedSpan<&'a str>;

struct Token<'a> {
    pub position: Span<'a>,
    pub foo: &'a str,
    pub bar: &'a str,
}

fn parse_foobar(s: Span) -> IResult<Span, Token> {
    let (s, _) = take_until("foo")(s)?;
    let (s, pos) = position(s)?;
    let (s, foo) = tag("foo")(s)?;
    let (s, bar) = tag("bar")(s)?;

    Ok((
        s,
        Token {
            position: pos,
            foo: foo.fragment,
            bar: bar.fragment,
        },
    ))
}

fn main() {
    let input = Span::new("Lorem ipsum \n foobar");
    let output = parse_foobar(input);
    let position = output.unwrap().1.position;
    assert_eq!(
        position,
        Span {
            offset: 14,
            line: 2,
            fragment: "",
            extra: (),
        }
    );
    assert_eq!(position.get_column(), 2);
}
```

This doesn't compile; the fields `offset`, `line`, and `fragment` are private in `Span`, and it doesn't seem like there are even builders or setters for these. I see why, in normal operation, you would never want to modify these; but I also see why it's a massive ergonomics hit to have to call a bunch of getters on your `position` instead of being able to construct an `expected` value to equate against.

Is there a standard workaround?

**Comment by ProgVal** [comment]
Oops, we forgot to update this example, good catch.

You can find the updated version here: https://docs.rs/nom_locate/3.0.0/nom_locate/

Unfortunately we don't have a replacement with better ergonomics than that.
