### ISSUE TITLE
LocatedSpan doesn't implement the len method.

### ISSUE THREAD

**Issue by zaphar** [fflorent/nom_locate#8]
Nom's separated_nonempty_list! and related macros relies on the presence of a len method: file:///Users/jwall/lib/rust/ucg/target/doc/src/nom/multi.rs.html#121

LocatedSpan doesn't support this method so if you use those macros it will fail. You can work around it with map_res! and a custom function but it would be nice if LocatedSpan supported this out of the box.

**Comment by fflorent** [comment]
Hi and thanks for the report!

My guess is that Nom shouldn't use `.len()` directly but rather `.input_len()`, so I submitted a PR there. Let's see the feedback on it ;).

Florent

**Comment by fflorent** [comment]
Hi there!

The PR has been merged, the only thing we have to do now is to wait a new release of nom :).

Florent

**Comment by ProgVal** [comment]
I believe this is now fixed. Closing the issue.
