### ISSUE TITLE
Serializing LocatedSpan as a remote using Serde

### ISSUE THREAD

**Issue by AntoineBalaine** [fflorent/nom_locate#86]
Hello,

I'm grappling implementing Serialize for `LocatedSpan`.  
Because of rust's orphan rule, serializing the struct requires creating a remote-definition, and a wrapper struct. Full link to the implementation, [here](https://github.com/AntoineBalaine/abc_parser/blob/main/src/serializer.rs).

the remote definition has the following setup
```rust
#[derive(Serialize, PartialEq, Eq)]
#[serde(remote = "LocatedSpan")]
struct RemoteSpanDef<T: AsBytes + Serialize> {
  //...methods here
}
```

and the wrapper struct follows as such: 
```rust
#[derive(serde::Serialize, Clone, Copy, Debug)]
pub struct Span<T: AsBytes + Serialize>(#[serde(with = "RemoteSpanDef")] LocatedSpan<T>);
```

Serializing a `LocatedSpan<&'a str>` from here works wonders. Only, getting to use the resulting type in the context of a nom parser shows me a bunch of missing Traits, no matter what I do:

```rust
fn parse_thing<'a, T: AsBytes + Serialize>(input: Span<T>) -> IResult<Span<T>, Span<T>> {
    alt((tag("mytag"),))(input) //<= the trait bound `Span<T>: InputTake` is not satisfied
}
```

I'm confused about having to add in traits that already exist in the wrapped struct. Am I going to have to re-do the implementation of all of nom's required traits, or is there another way around ?

**Comment by progval** [comment]
Did you look into this? https://docs.rs/newtype_derive/latest/newtype_derive/

**Comment by AntoineBalaine** [comment]
I just did, and I'm not sure how to use that crate. The traits that it derives are not the same ones as nom's (AsBytes, InputTakeAtPosition, InputLength, etc.), so it's not really possible to use it to derive the LocatedSpan's inner workings. 
Could you nudge me in the right direction please?

**Comment by progval** [comment]
I mean, I don't have the solution, but you could look at the crate for a solution.

if I understand https://github.com/DanielKeep/rust-custom-derive/blob/master/newtype_derive/src/lib.rs correctly, they are indeed manually implementing all the trait (with macros to deduplicate some of the syntax), so it does look like doing it manually is the only way. You might be able to reuse (or copy) the macros though
