### ISSUE TITLE
Use without std

### ISSUE THREAD

**Issue by Michael-F-Bryan** [fflorent/nom_locate#9]
Nom can be used without the standard library (e.g. with `#![no_std]`), what are your thoughts on enabling this crate to be used in a `no_std` context as well?

Briefly looking through the source code, this crate doesn't seem to explicitly *need* anything from `std`. The `memchr` crate also seems to have a `no_std` feature, so you shouldn't need to reimplement `memchr::memrchr()`.

**Comment by fflorent** [comment]
Hi! Sorry for having taken long to answer you.

Of course that's a great idea! I plan to work on this during the month, I am a bit busy currently :).

Florent
